<a href="https://colab.research.google.com/github/asdsadawww/-/blob/main/Colab_%ED%8C%8C%EC%9D%B4%EC%8D%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Colab 시작 페이지

In [41]:
import pandas as pd
import seaborn as sns
import numpy as np

In [ ]:
score=[80,60,70,50,90]
score

[80, 60, 70, 50, 90]

In [ ]:
sum(score)

350

In [ ]:
sum_score=sum(score)

In [ ]:
sum_score

350

In [ ]:
df=pd.DataFrame({'name'    :['김지훈','이유진','박동현','김민지'],
                 'english' :[90,80,60,70],
                 'math'    :[50,60,100,20]})
df

  name  english  math
0  김지훈       90    50
1  이유진       80    60
2  박동현       60   100
3  김민지       70    20

In [ ]:
sum(df['english'])

300

In [ ]:
sum(df['math'])

230

In [ ]:
sum(df['english'])/4

75.0

In [ ]:
sum(df['math'])/4

57.5

In [ ]:
df=pd.DataFrame({'제품'   :['사과','딸기','수박'],
                 '가격'   :[1800,1500,3000],
                 '판매량' :[24,38,13]})
df

   제품    가격  판매량
0  사과  1800   24
1  딸기  1500   38
2  수박  3000   13

In [ ]:
sum(df['가격'])

6300

In [ ]:
sum(df['가격'])/3

2100.0

In [ ]:
sum(df['판매량'])

75

In [ ]:
sum(df['판매량'])/3

25.0

In [12]:
df_exam = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/exam.csv')
df_exam

    id  nclass  math  english  science
0    1       1    50       98       50
1    2       1    60       97       60
2    3       1    45       86       78
3    4       1    30       98       58
4    5       2    25       80       65
5    6       2    50       89       98
6    7       2    80       90       45
7    8       2    90       78       25
8    9       3    20       98       15
9   10       3    50       98       45
10  11       3    65       65       65
11  12       3    45       85       32
12  13       4    46       98       65
13  14       4    48       87       12
14  15       4    75       56       78
15  16       4    58       98       65
16  17       5    65       68       98
17  18       5    80       78       90
18  19       5    89       68       87
19  20       5    78       83       58

In [10]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
sum(df_exam['english']) # 총 합

1698

In [ ]:
sum(df_exam['english'])/20 # 총 20명

84.9

In [ ]:
sum(df_exam['science'])/20

59.45

In [ ]:
df=pd.DataFrame({'a':[1,2,3],
                 'b':[4,5,6]})

In [ ]:
df

   a  b
0  1  4
1  2  5
2  3  6

In [ ]:
len(df)

3

In [ ]:
len(df_exam)   #df_exam 행의 개수

20

In [ ]:
sum(df_exam['english'])/len(df_exam['english'])   #영어 평균

84.9

In [ ]:
sum(df_exam['science'])/len(df_exam['science'])   #과학 평균

59.45

In [ ]:
df_midterm=pd.DataFrame({'english' :[90,80,60,70],
                         'math'    :[50,60,100,20],
                         'nclass'  :[1,1,2,2]})
df_midterm

   english  math  nclass
0       90    50       1
1       80    60       1
2       60   100       2
3       70    20       2

In [ ]:
df_midterm.to_csv('output_newdata.csv')

In [16]:
exam=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/exam.csv')

In [20]:
exam.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [19]:
exam.shape

(20, 5)

In [21]:
exam.describe()

             id     nclass       math    english    science
count  20.00000  20.000000  20.000000  20.000000  20.000000
mean   10.50000   3.000000  57.450000  84.900000  59.450000
std     5.91608   1.450953  20.299015  12.875517  25.292968
min     1.00000   1.000000  20.000000  56.000000  12.000000
25%     5.75000   2.000000  45.750000  78.000000  45.000000
50%    10.50000   3.000000  54.000000  86.500000  62.500000
75%    15.25000   4.000000  75.750000  98.000000  78.000000
max    20.00000   5.000000  90.000000  98.000000  98.000000

In [23]:
mpg=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/mpg.csv')
mpg

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [24]:
mpg.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [25]:
mpg.tail()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class
229,volkswagen,passat,2.0,2008,4,auto(s6),f,19,28,p,midsize
230,volkswagen,passat,2.0,2008,4,manual(m6),f,21,29,p,midsize
231,volkswagen,passat,2.8,1999,6,auto(l5),f,16,26,p,midsize
232,volkswagen,passat,2.8,1999,6,manual(m5),f,18,26,p,midsize
233,volkswagen,passat,3.6,2008,6,auto(s6),f,17,26,p,midsize

In [26]:
mpg.shape

(234, 11)

In [27]:
mpg.describe()

            displ         year         cyl         cty         hwy
count  234.000000   234.000000  234.000000  234.000000  234.000000
mean     3.471795  2003.500000    5.888889   16.858974   23.440171
std      1.291959     4.509646    1.611534    4.255946    5.954643
min      1.600000  1999.000000    4.000000    9.000000   12.000000
25%      2.400000  1999.000000    4.000000   14.000000   18.000000
50%      3.300000  2003.500000    6.000000   17.000000   24.000000
75%      4.600000  2008.000000    8.000000   19.000000   27.000000
max      7.000000  2008.000000    8.000000   35.000000   44.000000

In [31]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/exam.csv')
df.head()

   id  nclass  math  english  science
0   1       1    50       98       50
1   2       1    60       97       60
2   3       1    45       86       78
3   4       1    30       98       58
4   5       2    25       80       65

In [32]:
type(df)

pandas.core.frame.DataFrame

In [37]:
type(var)

list

In [43]:
df_raw=pd.DataFrame({'var1' :[1,2,1],
                     'var2' :[2,3,2]})
df_raw

   var1  var2
0     1     2
1     2     3
2     1     2

In [46]:
df=pd.DataFrame({'var1' :[4,3,8],
                 'var2' :[2,6,1]})
df

   var1  var2
0     4     2
1     3     6
2     8     1

In [47]:
df['var_sum']=df['var1']+df['var2']
df

   var1  var2  var_sum
0     4     2        6
1     3     6        9
2     8     1        9

In [50]:
df['var_mean']=(df['var1']+df['var2'])/2
df

   var1  var2  var_sum  var_mean
0     4     2        6       3.0
1     3     6        9       4.5
2     8     1        9       4.5

In [52]:
mpg['total']=(mpg['cty']+mpg['hwy']) /2  #통합연비 변수만들기
mpg.head()

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,class,total
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact,23.5
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact,25.0
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact,25.5
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact,25.5
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact,21.0

In [55]:
sum(mpg['total'])/ len(mpg)  #total합계를 행 수로 나누

20.14957264957265